version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    command: serve
    volumes:
      - "/mnt/user/docker/volumes/diun/:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=America/Chicago"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_DOCKER=true"
      # Discord
      - "DIUN_NOTIF_DISCORD_WEBHOOKURL=${DIUN_DISCORD_WEBHOOK}"
      - "DIUN_NOTIF_DISCORD_RENDERFIELDS=alexanderscott"
      - "DIUN_NOTIF_DISCORD_TIMEOUT=10s"
      - "DIUN_NOTIF_DISCORD_TEMPLATEBODY= Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released."
    labels:
      - "diun.enable=true"
