version: "3.9"

configs:
  customization:
    name: configuration_${TAG}
    file: ./config.yaml

services:
  diun:
    image: crazymax/diun:4.29.0
    configs: 
      - source: customization
        target: /etc/diun/diun.yaml
    command: serve
    volumes:
      - "/mnt/user/docker/volumes/diun/:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=America/Chicago"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_SWARM=true"
      # Discord
      - "DIUN_NOTIF_DISCORD_WEBHOOKURL=${DIUN_NOTIF_DISCORD_WEBHOOKURL}"
    labels:
      - diun.enable=true
