name: 'diun'
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure application
        env:
          DIUN_NOTIF_DISCORD_WEBHOOKURL: ${{ secrets.DIUN_NOTIF_DISCORD_WEBHOOKURL }}
        run: |
          sed -i 's/${DIUN_NOTIF_DISCORD_WEBHOOKURL}/'${DIUN_NOTIF_DISCORD_WEBHOOKURL}'/' config.yaml
          cat config.yaml
      - name: Run a container command
        env:
          TAG: ${{ github.sha }}
        run: |
          docker stack deploy -c diun.yaml diun
