name: 'diun'
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]
    env:
      DIUN_NOTIF_DISCORD_WEBHOOKURL: ${{ secrets.DIUN_NOTIF_DISCORD_WEBHOOKURL }}
      TAG: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run a container command
        run: |
          docker stack deploy -c diun.yaml diun
